//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFE_Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCFE_Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;&lt;AddIns&gt;&lt;AddIn name=&quot;Sample Add-In&quot; description=&quot;Loaded from a journal file.&quot; assembly=&quot;Samples\V16\SampleAddIn\SampleAddIn.dll&quot; typename=&quot;SpaceClaim.Api.V18.Examples.SampleAddIn&quot; host=&quot;SameAppDomain&quot; /&gt;&lt;/AddIns&gt;.
        /// </summary>
        internal static string AddInManifestInfo {
            get {
                return ResourceManager.GetString("AddInManifestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap APIpython {
            get {
                object obj = ResourceManager.GetObject("APIpython", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,10S,10.3,1.24
        ///6,40S,10.3,1.73
        ///6,80S,10.3,2.41
        ///8,10S,13.7,1.65
        ///8,40S,13.7,2.24
        ///8,80S,13.7,3.02
        ///10,10S,17.1,1.65
        ///10,40S,17.1,2.31
        ///10,80S,17.1,3.2
        ///15,5S,21.3,1.65
        ///15,10S,21.3,2.11
        ///15,40S,21.3,2.77
        ///15,80S,21.3,3.73
        ///20,5S,26.7,1.65
        ///20,10S,26.7,2.11
        ///20,40S,26.7,2.87
        ///20,80S,26.7,3.91
        ///25,5S,33.4,1.65
        ///25,10S,33.4,2.77
        ///25,40S,33.4,3.38
        ///25,80S,33.4,4.55
        ///32,5S,42.2,1.65
        ///32,10S,42.2,2.77
        ///32,40S,42.2,3.56
        ///32,80S,42.2,4.85
        ///40,5S,48.3,1.65
        ///40,10S,48.3,2.77
        ///40,40S,48.3,3.68
        ///40,80S,48.3,5.08
        ///50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string asme_pipes {
            get {
                return ResourceManager.GetString("asme_pipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a filter for body selection..
        /// </summary>
        internal static string BodySelectHint {
            get {
                return ResourceManager.GetString("BodySelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body/Surface Filter.
        /// </summary>
        internal static string BodySelectText {
            get {
                return ResourceManager.GetString("BodySelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cpec_image {
            get {
                object obj = ResourceManager.GetObject("cpec_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps_image {
            get {
                object obj = ResourceManager.GetObject("cps_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreateAssembly {
            get {
                object obj = ResourceManager.GetObject("CreateAssembly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks edges between cylinders and planes..
        /// </summary>
        internal static string CylPlEdChHint {
            get {
                return ResourceManager.GetString("CylPlEdChHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder-Plane Edge Checker.
        /// </summary>
        internal static string CylPlEdChText {
            get {
                return ResourceManager.GetString("CylPlEdChText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate cylindrical corners of rounded rectangles from the straight sides..
        /// </summary>
        internal static string CylPlSepHint {
            get {
                return ResourceManager.GetString("CylPlSepHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder-Plane Seperator.
        /// </summary>
        internal static string CylPlSepText {
            get {
                return ResourceManager.GetString("CylPlSepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tool.
        /// </summary>
        internal static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sat geomerty export by material..
        /// </summary>
        internal static string ExportTextHint {
            get {
                return ResourceManager.GetString("ExportTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindMatchingFaces {
            get {
                object obj = ResourceManager.GetObject("FindMatchingFaces", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ga_image {
            get {
                object obj = ResourceManager.GetObject("ga_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assess geometry for surfaces and edges which need simplification before MCNP conversion..
        /// </summary>
        internal static string GeomAssHint {
            get {
                return ResourceManager.GetString("GeomAssHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Assessor.
        /// </summary>
        internal static string GeomAssText {
            get {
                return ResourceManager.GetString("GeomAssText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lost particle locations..
        /// </summary>
        internal static string LostParticlesHint {
            get {
                return ResourceManager.GetString("LostParticlesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost Particles.
        /// </summary>
        internal static string LostParticlesText {
            get {
                return ResourceManager.GetString("LostParticlesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight bodies with many surfaces.
        /// </summary>
        internal static string MaxSurfaceHint {
            get {
                return ResourceManager.GetString("MaxSurfaceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Surfaces.
        /// </summary>
        internal static string MaxSurfaceText {
            get {
                return ResourceManager.GetString("MaxSurfaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mtc_image {
            get {
                object obj = ResourceManager.GetObject("mtc_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot a Mesh Tally from an MCNP input file.
        /// </summary>
        internal static string MTCHint {
            get {
                return ResourceManager.GetString("MTCHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh Tally Checker.
        /// </summary>
        internal static string MTCText {
            get {
                return ResourceManager.GetString("MTCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mtw_image {
            get {
                object obj = ResourceManager.GetObject("mtw_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the Mesh Tally input for MCNP.
        /// </summary>
        internal static string MTWHint {
            get {
                return ResourceManager.GetString("MTWHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh Tally Writer.
        /// </summary>
        internal static string MTWText {
            get {
                return ResourceManager.GetString("MTWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string PartGroupText {
            get {
                return ResourceManager.GetString("PartGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pipe {
            get {
                object obj = ResourceManager.GetObject("pipe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifies pipes with a user specifed outer and (optional) inner radius.
        /// </summary>
        internal static string Pipes_simp_2_hint {
            get {
                return ResourceManager.GetString("Pipes_simp_2_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify Pipes Specifed Radius.
        /// </summary>
        internal static string Pipes_simp_2_text {
            get {
                return ResourceManager.GetString("Pipes_simp_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifies pipes using the radius of the pipe.
        /// </summary>
        internal static string Pipes_simp_hint {
            get {
                return ResourceManager.GetString("Pipes_simp_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify Pipes.
        /// </summary>
        internal static string Pipes_simp_text {
            get {
                return ResourceManager.GetString("Pipes_simp_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate sections of simplified pipes.
        /// </summary>
        internal static string PiSepHint {
            get {
                return ResourceManager.GetString("PiSepHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe Seperator.
        /// </summary>
        internal static string PiSepText {
            get {
                return ResourceManager.GetString("PiSepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ps_image {
            get {
                object obj = ResourceManager.GetObject("ps_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab id=&quot;CCFE_Toolbox.C#.V18.RibbonTab&quot; command=&quot;CCFE_Toolbox.C#.V18.RibbonTab&quot;&gt;
        ///				&lt;!-- 
        ///					For the &apos;tab&apos; and &apos;group&apos; elements, you can either specify a &apos;label&apos; attribute, or you can
        ///					specify a &apos;command&apos; attribute.  The &apos;command&apos; attribute gives the name of a command that you
        ///					create, whose Text property will be used for the label.  This approach allows for localization        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCFE Toolkit.
        /// </summary>
        internal static string RibbonTabText {
            get {
                return ResourceManager.GetString("RibbonTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SceneGraph {
            get {
                object obj = ResourceManager.GetObject("SceneGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SketchTool {
            get {
                object obj = ResourceManager.GetObject("SketchTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tori_image {
            get {
                object obj = ResourceManager.GetObject("tori_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify tori into a number of cylinders.
        /// </summary>
        internal static string toriHint {
            get {
                return ResourceManager.GetString("toriHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify Tori.
        /// </summary>
        internal static string toriText {
            get {
                return ResourceManager.GetString("toriText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap va_image {
            get {
                object obj = ResourceManager.GetObject("va_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives the component volumes at a specified structure tree depth..
        /// </summary>
        internal static string VAHint {
            get {
                return ResourceManager.GetString("VAHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Assessor.
        /// </summary>
        internal static string VAText {
            get {
                return ResourceManager.GetString("VAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vg_image {
            get {
                object obj = ResourceManager.GetObject("vg_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap void_Image {
            get {
                object obj = ResourceManager.GetObject("void_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate void cells.
        /// </summary>
        internal static string VoiGenHint {
            get {
                return ResourceManager.GetString("VoiGenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Generator.
        /// </summary>
        internal static string VoiGenText {
            get {
                return ResourceManager.GetString("VoiGenText", resourceCulture);
            }
        }
    }
}
